verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
say-on-exit   = false
glob_ignores  = ['.git', '.DS_Store', "__pycache__"]
subtask-sleep = 1
batch-sleep   = 1

[tool.doot.directories]
src     = "cairo_utils"
codegen = "cairo_utils/_codegen"
temp    = ".temp"
build   = "build"
docs    = "docs"
data    = "data"
