[colours]
TEXT              = [0, 1, 1, 1]
EDGE              = [1, 0, 0, 1]
VERTEX            = [1, 0, 1, 1]
FACE              = [0, 0, 1, 1]
START             = [0, 1, 0, 1]
END               = [1, 0, 0, 1]
BACKGROUND        = [0, 0, 0, 1]
FRONT             = [0.8, 0.1, 0.71, 0.5]
FACE_COLOUR       = [0.2, 0.2, 0.9, 1]
EDGE_COLOUR       = [0.4, 0.8, 0.1, 1]
VERT_COLOUR       = [0.9, 0.1, 0.1, 1]
BACKGROUND_COLOUR = [0, 0, 0, 1]

[data]
#The number of items in a sample
# Currently: [x,y, rad, r,g,b,a]
sample_items = 7
#Data Required for a line:
line_items   = 4
#Data required for a bezier:
bezier_items = 8
#Data required for a circle:
circle_items = 6
#COLOUR SIZE
colour_itmes = 4
